### ISSUE TITLE
Issue with kerning panel display

### ISSUE THREAD

**Issue by gorjious** [yanone/spacebar#1]
I use the left and right sidebearing panels extensively, they make it very easy to see the changes across masters. Recently, I tried to use the Kerning panel and noticed that it doesn't seem to function the same way. If masters have the same weight value then the dots are along the same verticals and the kerning values overlap. If the masters have different weight values then the dots are spaced along the horizontal, however, if the weights are too close, the kerning values overlap. 

From the images on your site, it seems that the Kerning panel should display similar to the Sidebearing panel with evenly spaced dots and values. 

Not sure if this has to do with plugin or the latest version of glyphs. I am using SpaceBar v1.07 and Glyphs Version 2.6.5 (1312) 

<img width="158" alt="Screenshot 2020-04-06 at 17 05 57" src="https://user-images.githubusercontent.com/23149420/78613366-eb4df080-7828-11ea-8027-1f3df8a5eea2.png">

**Comment by yanone** [comment]
Hi @gorjious,
it's always easier to look at these things with the respective file loaded. Would you please send me your glyphs file for reference to post@yanone.de? Obviously, I will treat it confidentially. Thanks.

**Comment by FAlthausen** [comment]
Same here. 
12 masters, three axes (wght, wdth, opsz). 
Why not simply show the masters in their order like they are in the font info? (Same for side bearings panels)
I’d appreciate a fix very much!
Can’t use the plugin like that. 🙁

**Comment by yanone** [comment]
I uploaded the fixed plugin just now. Glyphs should pull the update on app start, but I'm not 100% sure. Please check and let me know.

**Comment by gorjious** [comment]
I had to remove and reinstall the plugin. The kerning panel in v1.08 now works. 
Thank you for this update!

**Comment by FAlthausen** [comment]
Yeah, great. Looks very good. Thank you so much!
(I had to remove and reinstall it too. I guess Glyphs points to plugin updates only when it updates itself.)
