### ISSUE TITLE
Bug where kerning panel remains empty

### ISSUE THREAD

**Issue by FAlthausen** [yanone/spacebar#2]
I think I found another little bug where sometimes Spacebar’s kerning panel remains (completely) empty even though there is kerning.
According to my observation this could be related to longer kerning group names like "shoulder" or "LC_shortStem". Could that be?
Thanks, Jan!

**Comment by yanone** [comment]
Send me the font please

**Comment by uebele** [comment]
Space Bar goes completely away when there is a kerning pair. Also, Glyphs wouldn’t show the info field with the spacing and kerning values. I’m in Glyphs 3.

**Comment by RafalBuchner** [comment]
@uebele, check out if it works for you with version 1.11 for glyphs 3
https://github.com/yanone/spacebar/archive/refs/heads/glyphs3.zip

**Comment by uebele** [comment]
Yes, it works now perfectely, thanks!
